-- require("core.plugin_config.gruvbox")
-- require("core.plugin_config.nord-vim")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.fugitive")
require("core.plugin_config.lsp_config")
require("core.plugin_config.aerial")
require("core.plugin_config.autocmd")
require("core.plugin_config.completions")
require("core.plugin_config.copilot")
require("core.plugin_config.prettier")
-- require("core.plugin_config.ale")
require("core.plugin_config.flutter_tools")
